### PR TITLE
Fixes error `attempt to insert nil object from objects[2] was thrown while invoking readDir on target`

### PR DESCRIPTION
**Pull request by jeduan**
This error happens when trying to read a file or directory for which the user doesn't have permissions. Doing this will throw the error below. This pull request skips over any file that throws an error when trying to read the attributes. Also skips over any dotfile found on the directory.

simulator_screen_shot_apr_13 _2016 _9 35 07_am

### CODE REVIEW

**Comment by jeduan** [comment]
This is related to #75

**Comment by johanneslumpe** [comment]
@jeduan I'm not sure that just skipping the files is expected behavior? This is like silently failing, which might be even more confusing to users?

**Comment by jeduan** [comment]
Good point, should I rather break the loop and send an error the moment I get this?

**Comment by johanneslumpe** [comment]
When this error occurs, that means that we cannot read any file in the directory, right? Because it would always break for those files. I think instead of skipping over those files or just failing hard, we might want to send an object with the filename and a custom error prop, so we can continue with the rest but the user will still know that the file failed. Then the user itself could filter the result to get rid of those files from the list maybe? What do you think about that? Just a suggestion though, nothing set in stone.

**Comment by jeduan** [comment]
So the case I have is: (on iOS Simulator)

 - Read `/`
 - Will get info for every file/directory
 - When it reaches `/dev` it throws

That's why I just skipped over the directory that fails. Your solution seems reasonable, too. I can implement it if you want to go that way.

**Comment by johanneslumpe** [comment]
@jeduan Did you ever get around to add the custom error object instead of just skipping over a file?

**Comment by felgaaen** [comment]
Can you please merge this if the problem is solved? Still experiencing the issue

**Comment by thanmaic** [comment]
Still experiencing the issue. Any fix or work around to this issue?
@jeduan @itinance 

RN version: 0.63.3
react-native-fs version: 2.13.3

**Comment by jeduan** [comment]
This is over 4 years old. @thanmaic feel free to open a new PR based on this.

**Pull request closed without merging**
