### PR TITLE
IOS: File Protection Support

### PR DESCRIPTION
**Pull request by gensc004**
Adding support for specifying IOS File Protections when creating/moving/copying files, and making directories.

### CODE REVIEW

**Comment by itinance** [comment]
Pretty cool! Thank you very much!

**Comment by AlexanderZaytsev** [comment]
@gensc004 could you please provide an example on how to use it? Should it be something like this?
```javascript
RNFS.writeFile(path, data, { NSFileProtectionKey: 'NSFileProtectionComplete'})
```

**Comment by gensc004** [comment]
@AlexanderZaytsev Unfortunately its been a while since I made this PR, and I don't have an example of implementing it my project anymore. Based on what I remember, and looking through the code again, it does look like that example you gave should work! Did you get a chance to test it out?

**Comment by Fannolo** [comment]
@AlexanderZaytsev from what I saw in the code, correct me if I'm wrong, writeFile does not support NSFileProtectionKey, also DownloadFile seems to have the same problem.

**Pull request merged**
