### PR TITLE
Adds react-native-windows support for UWP

### PR DESCRIPTION
**Pull request by rozele**
This changeset includes most of the react-native-fs functionality working for UWP. Some notable missing features are:
* all of the `Assets` APIs (e.g., `readDirAssets`, `existsAssets`, etc.) that are Android specific
* the `pathForBundle` and `pathForGroup` APIs that are iOS specific
* the `uploadFiles` API, which just has not yet been implemented.

### CODE REVIEW

**Comment by rozele** [comment]
@itinance any chance we can get this merged?

**Comment by itinance** [comment]
Hell yes, thank you :) My issue was that i haven't any windows system here to test it. Since it doesnt effect any existing code for iOS and Android i will merge now.

**Comment by itinance** [comment]
@rozele Would you mind providing a section in README.md for UWP-support? Thank you!

**Comment by rozele** [comment]
@itinance of course! I'll try to write something up this week!

**Comment by itinance** [comment]
Great. It would be part then of next release.

**Pull request merged**
