### PR TITLE
Replace deprecated 'compile' gradle configuration with 'implementation

### PR DESCRIPTION
**Pull request by mars-lan**
See http://d.android.com/r/tools/update-dependency-configurations.html for more details

### CODE REVIEW

**Comment by itinance** [comment]
thx!

**Comment by skb1129** [comment]
@itinance This is a breaking change, it works with Gradle version 3+ only and Gradle 3+ is available in react native version 0.57.0+

**Comment by itinance** [comment]
@skb1129 any advice how to make it backwards compatible?

**Comment by itinance** [comment]
One option could be that older RN versions should be fixed with v2.11.17:
 https://github.com/itinance/react-native-fs/tree/v2.11.17

**Comment by skb1129** [comment]
@itinance Yeah older RN versions can use v2.11.17
You should release v2.12.0 for these changes.

**Comment by skb1129** [comment]
And also mention this as a breaking change in the release notes

**Pull request merged**
