### PR TITLE
Add basic support for Android content URIs in stat

### PR DESCRIPTION
**Pull request by stevenremot**
Add a basic implementation of stat for content URIs that returns what
it can return: the file length.

This also raises the Android SDK API requirements of this method from 1 to 3, which is... fine I guess ?

If you see anything else I can return for a content URI I will be glad to add it.

### CODE REVIEW

**Review by viveking — CHANGES_REQUESTED** [review]
It seems you not providing.
- ctime , mtime, type[MIME], orginalFilepath 

Please handle the same.

**Comment by stevenremot** [comment]
Thanks for the feedback! It doesn't look as straightforward as the non-content schemes, but I will have a look at it.

**Comment by stevenremot** [comment]
It's been a month and I haven't been able to take a look at it. I'm not sure I will be able to in the near future. So feel free to close this PR if you want to keep the project clean.

**Comment by itinance** [comment]
Alright. I'm going to close this as you suggested. Pls feel free everybody to bring this to life later.

**Pull request closed without merging**
