### PR TITLE
getContentLengthLong requires API 24

### PR DESCRIPTION
**Pull request by a-koka**
Reverted getContentLengthLong to getContentLength to support API 16.

### CODE REVIEW

**Comment by a-koka** [comment]
Fixes #606

**Comment by itinance** [comment]
Thx for PR. The discussion happens already here: https://github.com/itinance/react-native-fs/issues/606

**Comment by a-koka** [comment]
This should be merge-ready. Please let me know if it needs changes. Thank you!

**Comment by itinance** [comment]
thx man!

**Pull request merged**
