### PR TITLE
Closes #46 - 'RCTBridgeModule.h' file not found error

### LINKED ISSUE #46: Build Failed on iOS
There is an error: 'RCTBridgeModule.h' file not found.

### PR DESCRIPTION
**Pull request by iSimar**
This PR for the fix of issue: https://github.com/johanneslumpe/react-native-fs/issues/46

### CODE REVIEW

**Comment by cjdell** [comment]
This is more of a workaround than a fix. If you create a new app with the CLI tool it will use arrow brackets. We should find out why arrow brackets isn't working in this case.

**Comment by iSimar** [comment]
@cjdell hmm...interesting. you're right.

**Comment by clarkie** [comment]
@cjdell which CLI tool are you referencing?

**Comment by itinance** [comment]
This PR would break compatibility with ReactNative >= 0.40 (and in fact it will undo the changes that where necessary when 0.40 came out). 

If you are below RN 0.40, consider to use an older release of react-native-fs please.

**Pull request closed without merging**
