### PR TITLE
updated compilesdkversion and buildtoolsversion

### PR DESCRIPTION
**Pull request by The-Code-Monkey**
updated the build.gradle to 26 and 26.0.3

### CODE REVIEW

**Comment by RodolfoSilva** [comment]
@itinance I think we need to generate a new version with this PR, because any project with react-native0.56.0 will be broken when trying to use this project.

This PR will solve #517

**Comment by vieiralucas** [comment]
How long till this makes to npm?

**Comment by RodolfoSilva** [comment]
@itinance :point_up:

**Comment by ezailWang** [comment]
@itinance ☝️☝️

**Pull request merged**
