### PR TITLE
add missing typings for deprecated beginCallback and progressCallback

### PR DESCRIPTION
**Pull request by krystofbe**
fixes: https://github.com/itinance/react-native-fs/issues/537

### CODE REVIEW

**Comment by hhff** [comment]
:+1: would love to see this merged!

**Comment by skovhus** [comment]
Note that this is an issue for the flow version (`0.75.0`) shipped with the latest `react-native` version (`0.56.0`). 

This works. @tinance

**Comment by hhff** [comment]
Currently pointing @krystofbe's fork! I'm on 0.75.0, too

**Comment by skovhus** [comment]
@itinance anything we can do to release this?

**Comment by itinance** [comment]
Merged. Many thanks!

**Comment by matteodanelli** [comment]
Which version contains this fix?

**Pull request merged**
