### PR TITLE
Clarify react-native dependency to be >=0.51.0, < 1.0.0

### PR DESCRIPTION
**Pull request by Empact**
For 1.0.0 and above, caret means "matches major version",
but for 0.x.0 and above, caret means "matches major and minor version".

It's clear from usage that the intention for this dependency is to
match the looser 1.0.0 caret usage. This change matches that, enabling
explicit compatibility with react-native releases from the past 5 months.

https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
https://www.npmjs.com/package/react-native

### CODE REVIEW

**Comment by Empact** [comment]
Partially fixes #439

**Comment by sesam** [comment]
ping @Empact and maintainers, any love for this? Leaving warnings around unattended is creating a bad smell, mmkay :)

**Comment by Empact** [comment]
Resolved merge conflicts

**Comment by itinance** [comment]
Release is out. Thx for the reminder, @sesam !

**Pull request merged**
