### PR TITLE
Manually flush & invalidate completed session

### PR DESCRIPTION
**Pull request by n-sviridenko**

### CODE REVIEW

**Comment by joshuaellis** [comment]
Isnt this just the same as #938?

**Comment by n-sviridenko** [comment]
@joshuaellis you had a typo in the method Matas pointed out to so I created a separate branch as I wasn't able to push to yours.

**Comment by n-sviridenko** [comment]
flushWithComple**tion**Handler

**Comment by joshuaellis** [comment]
so i did. I'll just close my PR, no point there being two.

**Pull request merged**
